[package]
name = "rust_os"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust_os"
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.23"
volatile = "0.2.6"
